version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 4
- package-ecosystem: npm
  directory: "/examples/articles"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 2
- package-ecosystem: npm
  directory: "/examples/blocks"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 2
- package-ecosystem: npm
  directory: "/examples/button"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 2
- package-ecosystem: npm
  directory: "/examples/json"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 2
- package-ecosystem: npm
  directory: "/examples/masonry"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 2
- package-ecosystem: npm
  directory: "/examples/overflow"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 2
- package-ecosystem: npm
  directory: "/examples/vuejs"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 2
